global:
  domain: reitzrobert77.de

configs:
  params:
    server.insecure: true
    server.basehref: /argocd
  cm:
    application.resourceTrackingMethod: "annotation"
    timeout.reconciliation: 60s
    resource.exclusions: |
      - kinds:
          - ProviderConfigUsage
        apiGroups:
          - "*"

notifications:
  enabled: false

dex:
  enabled: false

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    path: /argocd(/|$)(.*)
    pathType: ImplementationSpecific
    extraTls:
      - hosts:
        - reitzrobert77.de
        secretName: argocd-net-tls

